<a href="https://colab.research.google.com/github/bruarana/Aprendizaje-Autom-tico/blob/main/Ejercicios%20Semana%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Ejercicio 1: Array de 10 ceros
import numpy as np

arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
#Ejercicio 2: Array del 1 al 20
arr2 = np.arange(1, 21)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#Ejercicio 3: Números pares del 2 al 50
arr3 = np.arange(2, 51, 2)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [4]:
#Ejercicio 5: Matriz 4x4 con valores aleatorios (0 a 1)
mat1 = np.random.rand(4, 4)
print(mat1)

[[0.74384652 0.15396695 0.07023775 0.68899483]
 [0.73349843 0.39252355 0.96309987 0.6277205 ]
 [0.76647382 0.1994862  0.36503711 0.72731501]
 [0.02397305 0.75195629 0.25715725 0.93567151]]


In [5]:
#Ejercicio 6: Suma elemento a elemento
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


In [6]:
#Ejercicio 7: Multiplicación de matrices 3x3
mat2 = np.random.randint(1, 11, (3, 3))
mat3 = np.random.randint(1, 11, (3, 3))

producto = np.dot(mat2, mat3)

print("Matriz A:\n", mat2)
print("Matriz B:\n", mat3)
print("Producto:\n", producto)

Matriz A:
 [[ 6  7  7]
 [ 8  4  4]
 [ 2 10  9]]
Matriz B:
 [[1 8 4]
 [4 7 4]
 [4 1 9]]
Producto:
 [[ 62 104 115]
 [ 40  96  84]
 [ 78  95 129]]


In [7]:
#Ejercicio 8: Array aleatorio (1 a 100) + estadísticas
arr4 = np.random.randint(1, 101, 15)

print("Array:", arr4)
print("Máximo:", np.max(arr4))
print("Mínimo:", np.min(arr4))
print("Promedio:", np.mean(arr4))

Array: [ 20   7  14  98 100  87  88  57  63  26  13  38  76  58  15]
Máximo: 100
Mínimo: 7
Promedio: 50.666666666666664


In [8]:
#Ejercicio 9: Matriz 5x5 (1 al 25) y diagonal
mat4 = np.arange(1, 26).reshape(5, 5)

diagonal = np.diag(mat4)

print(mat4)
print("Diagonal:", diagonal)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


In [9]:
#Ejercicio 10: Suma por filas y columnas
mat5 = np.random.randint(1, 21, (5, 5))

suma_filas = np.sum(mat5, axis=1)
suma_columnas = np.sum(mat5, axis=0)

print("Matriz:\n", mat5)
print("Suma filas:", suma_filas)
print("Suma columnas:", suma_columnas)

Matriz:
 [[11  3 12  3 20]
 [15 10 17  4 12]
 [ 8  9  2  3  9]
 [16 14  4 12  8]
 [ 6  9 14  7  5]]
Suma filas: [49 58 31 54 41]
Suma columnas: [56 45 49 29 54]
